### PR TITLE
ESM

### PR DESCRIPTION
**Pull request by dgilperez**

### CODE REVIEW

**Comment by dgilperez** [comment]
Ups! I did not mean to open this PR. 

I am working fast to have this package up to date, but this is far from ready. I might need to use it in prod though, so I released it. 

There is also a couple of extras I am not sure you're interested in: 

* ajv-keywords
* injecting "complete" schemas, with if-else statements and things that right now are not supported

but if you're, I'd be glad to open a proper PR later on

**Comment by andreidmt** [comment]
Hey @dgilperez,

- about `ajv-keywords`, I remember talking about it in #3. Im good to add it, think it's a good adition.
- about ESM, i've also wanted to do this for some time - here's where I want to take it https://github.com/asd-xiv/library-stack-node. I'll spend some time this weekend and make a PR for it - the main difficulty is other packages being non-esm or not playing nice (for ex "riteway"), hence blocking everything ... thank you sindresorhus - https://github.com/sindresorhus/meta/discussions/15

This is a also a good read on the ESM chaos - https://gist.github.com/joepie91/bca2fda868c1e8b2c2caf76af7dfcad3

**Comment by andreidmt** [comment]
I dont fully understand "injecting "complete" schemas, with if-else statements and things that right now are not supported" ... do you have an example?

**Comment by dgilperez** [comment]
Yeah, sorry for the telegraphic style, it was late :) 

* I did most of the work you mention towards ESM, but could not manage to make it work. I dropped _riteway_ in favour of _tape_, but it seems _pluginus_ needed a similar treatment ... and I got into a bit of a loop of require-input errors ... I am adding a PR though, you may want to start from there or cherry pick some things, instead of doing the work from scratch.
* `ajv-keywords` - yes, #3 got block for some reason then, related to npm version. It seems to be working now, I am adding a PR with the version we're using now. 
* The "complete schema": explanation in the same PR.
* That https://github.com/sindresorhus/meta/discussions/15 is gold, thank you.

**Pull request closed without merging**
