### PR TITLE
ESM

### PR DESCRIPTION
**Pull request by dgilperez**
This is kind of WIP, I could not make it work yet ... but hopefully it's of some help for you if you plan to do this change. Feel free to pick whatever or close it otherwise.

### CODE REVIEW

**Comment by andreidmt** [comment]
Will continue this, thank you. 
Like you mentioned in #4 it's also `pluginus` that needs updating.

**Comment by dgilperez** [comment]
Hey! I just wanted to ping here to check for plans and status - are you planning to move these projects to ESM anytime soon? Thanks and have a great Easter!

**Comment by andreidmt** [comment]
Hey @dgilperez. I updated this weekend `eslint-config`, `m` and `pluginus`. I'll do this next but dont know when exactly, I'll give this next weekend a shot.

**Comment by andreidmt** [comment]
Happy Easter, thank you for keeping in touch!

**Comment by dgilperez** [comment]
It's great to see this improving! 

I hope you had a good Easter too - cheers!

**Comment by dgilperez** [comment]
Hey Andrei, any news / blocks here? Anything I can help with - do you want me to try this PR again after pluginus is ESM ready? Cheers!

**Comment by dgilperez** [comment]
Ok @andreidmt so this is read-ish. 

* All tests green except for multipart, which just fails with a 409 that points me in the direction of an error on underlying `MULTIPART` ... which I saw now is an archived repo (are you removing those?)
* I renamed one test schema from JSON to JS. [See here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-import-json)

There are probably a number of things to improve here, but overall I am happy with having something working for now.

I am going to test-drive this and let you know.

**Comment by andreidmt** [comment]
Hey @dgilperez thanks for putting in the effort. Just pushed a branch #7 with:

- ESM
- Full stack update
- Circleci overhaul
- New quality of life tools (githooks, commitlint, lint-staged)

The 409 from the `MULTIPART` was from the `busboy` upgrade that changed their API - see [d9ceb0d](https://github.com/asd-xiv/blocks/pull/7/commits/d9ceb0db209a730086d0b7edf19495bfb19438de#diff-e865441e9a29badf6629dc3b895dfd0891fe55efcbe1be584cff39f21d514564)

**Comment by dgilperez** [comment]
Closed by https://github.com/asd-xiv/blocks/pull/7

**Pull request closed without merging**
